# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-09 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageid', models.IntegerField()),
                ('pageid', models.IntegerField()),
                ('imageurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageid', models.IntegerField()),
                ('typeid', models.IntegerField()),
                ('pageurl', models.URLField()),
                ('time', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('numbs', models.IntegerField()),
                ('firstimg', models.IntegerField()),
                ('otherimg', models.IntegerField()),
            ],
        ),
    ]
